### ISSUE TITLE
Update/Installation failing Debian 11

### ISSUE THREAD

**Issue by RealStickman** [ronivay/XenOrchestraInstallerUpdater#118]
When using the xo-install.sh script, the "installation" step fails for me when I select the update/install option.  

The installation and updating previously worked, though it has been a while since I last ran it.  
I also pulled the latest version of this script to make sure this issue isn't due to an outdated install script.  

Shortened output from script.  
```
...

[info] xo-server and xo-web build takes quite a while. Grab a cup of coffee and lay back

[..] Running installation

[fail] Something went wrong, exiting. Check /home/exu/XenOrchestraInstallerUpdater/logs/xo-install.log-202204191446 for more details and use rollback feature if needed

[fail] Removing /opt/xo/xo-builds/xen-orchestra-202204191446 because of failed installation.
```

I also included the full logfile:  
<details>
<summary><b>Logfile</b></summary>

```
+ command -v git
/usr/bin/git
+ cd . && git config --get remote.origin.url
https://github.com/ronivay/XenOrchestraInstallerUpdater.git
+ cd . && git status --porcelain
+ cd . && git fetch
+ cd . && git rev-parse --short HEAD
ec902a5
+ cd . && git rev-parse --short FETCH_HEAD
ec902a5
+ cd . && git diff --name-only @{upstream}| grep xo-install.sh
Running script version ec902a5 with config:

PORT="80"
INSTALLDIR="/opt/xo"
SELFUPGRADE=true
CONFIGUPDATE=true
REPOSITORY="https://github.com/vatesfr/xen-orchestra"
BRANCH="master"
PLUGINS="all"
AUTOUPDATE="true"
OS_CHECK="true"
ARCH_CHECK="true"
PRESERVE="3"

+ id -u
0
+ uname -m
x86_64
+ command -v xe
+ grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | grep -Eo '[0-9]{1,2}' | head -1
11
+ grep ^NAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g' | awk '{print $1}'
Debian
+ grep ^GRUB_DISTRIBUTOR /etc/default/grub | grep 'Xen Orchestra'
+ command -v yum
+ command -v apt-get
/usr/bin/apt-get
+ command -v systemctl
/usr/bin/systemctl
+ df -P -k '/opt' | tail -1 | awk '{print $4}'
23133016
+ grep MemTotal /proc/meminfo | awk '{print $2}'
2005460
+ pgrep -f xo-server
+ apt-get update
OK:1 http://security.debian.org/debian-security bullseye-security InRelease
OK:2 http://deb.debian.org/debian bullseye InRelease
OK:3 http://deb.debian.org/debian bullseye-updates InRelease
OK:4 https://deb.nodesource.com/node_14.x bullseye InRelease
OK:5 https://dl.yarnpkg.com/debian stable InRelease
Paketlisten werden gelesen…
+ apt-get install -y build-essential redis-server libpng-dev git libvhdi-utils python2-minimal lvm2 nfs-common cifs-utils curl ntfs-3g
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
build-essential ist schon die neueste Version (12.9).
cifs-utils ist schon die neueste Version (2:6.11-3.1).
curl ist schon die neueste Version (7.74.0-1.3+deb11u1).
git ist schon die neueste Version (1:2.30.2-1).
libpng-dev ist schon die neueste Version (1.6.37-3).
libvhdi-utils ist schon die neueste Version (20201204-3).
lvm2 ist schon die neueste Version (2.03.11-2.1).
nfs-common ist schon die neueste Version (1:1.3.4-6).
ntfs-3g ist schon die neueste Version (1:2017.3.23AR.3-4+deb11u1).
python2-minimal ist schon die neueste Version (2.7.18-3).
redis-server ist schon die neueste Version (5:6.0.16-1+deb11u2).
Das folgende Paket wurde automatisch installiert und wird nicht mehr benötigt:
  linux-image-5.10.0-10-amd64
Verwenden Sie »sudo apt autoremove«, um es zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
+ apt-get install -y apt-transport-https ca-certificates
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
apt-transport-https ist schon die neueste Version (2.2.4).
ca-certificates ist schon die neueste Version (20210119).
Das folgende Paket wurde automatisch installiert und wird nicht mehr benötigt:
  linux-image-5.10.0-10-amd64
Verwenden Sie »sudo apt autoremove«, um es zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
+ apt-get install gnupg -y
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
gnupg ist schon die neueste Version (2.2.27-2+deb11u1).
Das folgende Paket wurde automatisch installiert und wird nicht mehr benötigt:
  linux-image-5.10.0-10-amd64
Verwenden Sie »sudo apt autoremove«, um es zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
+ command -v setcap
/usr/sbin/setcap
+ command -v node
/usr/bin/node
+ command -v npm
/usr/bin/npm
+ node -v 2>/dev/null| grep -Eo '[0-9.]+' | cut -d'.' -f1
14
+ command -v yarn
/usr/bin/yarn
+ /bin/systemctl enable redis-server && /bin/systemctl start redis-server
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
+ /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
+ cd "/opt/xo/xo-src/xen-orchestra" && git pull --ff-only
Bereits aktuell.
+ cd .
+ rm -rf "/opt/xo/xo-builds/xen-orchestra-202204191446"
+ cp -r "/opt/xo/xo-src/xen-orchestra" "/opt/xo/xo-builds/xen-orchestra-202204191446"
+ cd /opt/xo/xo-builds/xen-orchestra-202204191446 && git rev-parse HEAD
4b9db257fda4cc3ce71392d146abbc4e30e441a2
+ cd /opt/xo/xo-builds/xen-orchestra-202204191446 && git rev-parse --short HEAD
4b9db257f
+ cd .
+ readlink -e /opt/xo/xo-server
/opt/xo/xo-builds/xen-orchestra-202202171114/packages/xo-server
+ cd /opt/xo/xo-server && git rev-parse HEAD
1dad6b37ef9efcc26376ec385689f53ec2653bf9
+ cd /opt/xo/xo-server && git rev-parse --short HEAD
1dad6b37e
+ cd .
Updating Xen Orchestra from '1dad6b37e' to '4b9db257f'
+ pgrep -f xo-server
+ cd /opt/xo/xo-builds/xen-orchestra-202204191446 && yarn && yarn build
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > eslint-config-standard@17.0.0-1" has incorrect peer dependency "eslint-plugin-n@^14.0.0".
warning "workspace-aggregator-4a8e4d06-116b-4849-b470-15b7d650ea23 > @xen-orchestra/fs > @aws-sdk/lib-storage@3.72.0" has unmet peer dependency "@aws-sdk/abort-controller@^3.0.0".
[5/5] Building fresh packages...
error /opt/xo/xo-builds/xen-orchestra-202204191446/node_modules/validate-with-xmllint: Command failed.
Exit code: 1
Command: node ./lib/validate-xmllint-installation.js
Arguments: 
Directory: /opt/xo/xo-builds/xen-orchestra-202204191446/node_modules/validate-with-xmllint
Output:
/opt/xo/xo-builds/xen-orchestra-202204191446/node_modules/validate-with-xmllint/lib/validate-xmllint-installation.js:10
    throw new Error("Failed to validate xmllint installation. All xml validations will fail.");
    ^

Error: Failed to validate xmllint installation. All xml validations will fail.
    at Object.<anonymous> (/opt/xo/xo-builds/xen-orchestra-202204191446/node_modules/validate-with-xmllint/lib/validate-xmllint-installation.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
+ rm -rf /opt/xo/xo-builds/xen-orchestra-202204191446
```

</details>

**Comment by ronivay** [comment]
Hi,

Looks like the latest commit in XO master branch (https://github.com/vatesfr/xen-orchestra/commit/4b9db257fda4cc3ce71392d146abbc4e30e441a2) has broken it. I'll report it onwards.

**Comment by ronivay** [comment]
Yeah let's keep this open for now

**Comment by ronivay** [comment]
alrighty, this is now fixed in https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/91d934efef725cde041f6c9dcd7f5dacc8438c4c
