### ISSUE TITLE
cant connect to xcpng

### ISSUE THREAD

**Issue by jwspec** [ronivay/XenOrchestraInstallerUpdater#17]
server.connect
{
  "id": "c51e19ea-a306-4c54-aeb7-b192b43b5bd5"
}
{
  "call": {
    "method": "session.login_with_password",
    "params": [
      "root",
      "my password"
    ]
  },
  "message": "Cannot read property 'then' of undefined",
  "name": "TypeError",
  "stack": "TypeError: Cannot read property 'then' of undefined
    at /etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/promise-toolbox/src/timeout.js:33:9
    at Promise._execute (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/promise.js:79:10)
    at timeout (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/promise-toolbox/src/timeout.js:14:9)
    at Xapi.<anonymous> (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xen-api/src/index.js:1137:22)
    at loop (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xen-api/src/index.js:1154:17)
    at Xapi.<anonymous> (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xen-api/src/index.js:1188:15)
    at Xapi.loop (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xen-api/src/index.js:1193:15)
    at Xapi._transportCall (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xen-api/src/index.js:1216:20)
    at Xapi.connect (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xen-api/src/index.js:424:16)
    at /etc/xo/xo-builds/xen-orchestra-201917021246/packages/xo-server/src/xo-mixins/xen-servers.js:268:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xo-server/dist/xo-mixins/xen-servers.js:34:103)
    at _next (/etc/xo/xo-builds/xen-orchestra-201917021246/packages/xo-server/dist/xo-mixins/xen-servers.js:36:194)
    at tryCatcher (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/etc/xo/xo-builds/xen-orchestra-201917021246/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)"
}

any help would be great Im no to smart when it comes to errors   thanks John
jwspec@hotmail.com

**Comment by ronivay** [comment]
Hi,

Have you got this to work at some point or is this complerely fresh situation? Are you able to connect to the host with xcp-ng center, so is the problem only with xen orchestra? Either way this sounds more like an issue in xen orchestra rather than this installation script.

You could try to switch the branch (from xo-install.cfg) to a tagged xen orchestra release (for example tags/xo-server-v5.35.0) instead of the master branch if it’s temporarily broken for some reason.

**Comment by jwspec** [comment]
HI
No Not working. I can connect with xcpng center no problem.
The build is on new Debian 9.8 vm.
Your script is only thing I added to vm. Every thing seems to function within zen orchestra. Just cant add the server. I just play around with this computer stuff not very smart on fixing it .
Thank you for replying      John

**Comment by ronivay** [comment]
Hi,

I just ran a fresh test install with debian 9.8 and this script, using xen orchestra master branch (aka default settings) and had no issues connecting to XCP-NG host. 

Based on this i suggest trying to get help from xen orchestra forums for example. I'm not familiar with the error message you're getting, so can't really help you with that unfortunately since it's not related to my installation script.

**Comment by ronivay** [comment]
Hi,

Check this out: https://xen-orchestra.com/forum/topic/1291/cannot-read-property-then-of-undefined/4

So there was a bug in master branch which was already fixed when i tested it. So you should have been good by using a tagged source like i suggested in earlier message. Now it should be just matter of running the update with my script and it should work fine.

**Comment by jwspec** [comment]
Hi ,
I did see that on the forum. Thanks for the replies I did get it up and running Your script is awesome
Thanks John

**Comment by ronivay** [comment]
Great! Glad to hear that you got it to work.
