### ISSUE TITLE
Ubuntu server 16.04.6 LTS install 

### ISSUE THREAD

**Issue by mrab95** [ronivay/XenOrchestraInstallerUpdater#19]
Hi I have tried to install your script and always get the same error what am I doing wrong?

logg 
```
Cloning into '/etc/xo/xo-src/xen-orchestra'...                                                                                         
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".            
warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".                      
{ SyntaxError: /etc/xo/xo-builds/xen-orchestra-201920032154/packages/xo-server/src/xapi/index.js: Identifier 'vm' has already been dec$
                                                                                                                                       
  575 |         : null                                                                                                                 
  576 |                                                                                                                                
> 577 |     const vm = await targetXapi._getOrWaitObject(                                                                              
      |           ^                                                                                                                    
  578 |       await targetXapi._importVm(stream, sr, onVmCreation)                                                                     
  579 |     )                                                                                                                          
  580 |                                                                                                                                
    at Object.raise (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:3849:17)                     
    at ScopeHandler.declareName (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:8817:12)         
    at Object.checkLVal (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:5535:22)                 
    at Object.checkLVal (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:2315:20)                 
    at Object.parseVarId (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:7975:10)                
    at Object.parseVarId (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:2568:11)                
    at Object.parseVar (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:7946:12)                  
    at Object.parseVarStatement (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:7771:10)         
    at Object.parseStatementContent (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:7358:21)     
    at Object.parseStatement (/etc/xo/xo-builds/xen-orchestra-201920032154/node_modules/@babel/parser/lib/index.js:7291:17)            
  pos: 15159,                                                                                                                          
  loc: Position { line: 577, column: 10 },                                                                                             
  code: 'BABEL_PARSE_ERROR' }                                                                                                          
 ^ ^  2                                                                                                                                
error Command failed with exit code 1.     
```

**Comment by ronivay** [comment]
Hi,

This is an issue with the actual source build of Xen Orchestra. Could be that master branch is broken at the moment due to some latest commit. You can try to switch the branch in xo-install.cfg to ”tags/xo-server-v5.37.0” so that it uses the latest tested release. Let me know if that works for you.
