### ISSUE TITLE
Can't run backups

### ISSUE THREAD

**Issue by BrianDLC** [ronivay/XenOrchestraInstallerUpdater#257]
Hi,

My setup:
Running a fresh install of the premade xo-ce VM from running this script:

sudo bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-vm-import.sh)"

Tested it on 2 different hosts/pools with same results, attempted to restore my backed up config of my previous xo-ce as well as manually connecting the pools and setting up a new backup job, however I am met with the error below.

This all started because I was running into an issue with lock file is already being held when running a Delta job one of my VM's, here is the error:

```
    {
      "data": {
        "type": "VM",
        "id": "aeb1be31-6610-8289-b185-beb02a8e3269",
        "name_label": "Panel+Docpoc4"
      },
      "id": "1725806118787",
      "message": "backup VM",
      "start": 1725806118787,
      "status": "failure",
      "warnings": [
        {
          "message": "the writer IncrementalRemoteWriter has failed the step writer.beforeBackup() with error Lock file is already being held. It won't be used anymore in this job execution."
        }
      ],
      "end": 1725806118871,
      "result": {
        "code": "ELOCKED",
        "file": "/opt/xo/mounts/e6bdefa2-9f82-4d9b-aae7-93ea36b23829/xo-vm-backups/aeb1be31-6610-8289-b185-beb02a8e3269",
        "message": "Lock file is already being held",
        "name": "Error",
        "stack": "Error: Lock file is already being held\n    at /opt/xo/xo-builds/xen-orchestra-202407042240/node_modules/proper-lockfile/lib/lockfile.js:68:47\n    at callback (/opt/xo/xo-builds/xen-orchestra-202407042240/node_modules/graceful-fs/polyfills.js:306:20)\n    at FSReqCallback.oncomplete (node:fs:198:5)\n    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)\nFrom:\n    at NfsHandler.addSyncStackTrace (/opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/fs/dist/local.js:21:26)\n    at NfsHandler._lock (/opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/fs/dist/local.js:135:48)\n    at NfsHandler.lock (/opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/fs/dist/abstract.js:232:27)\n    at IncrementalRemoteWriter.beforeBackup (file:///opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/backups/_runners/_writers/_MixinRemoteWriter.mjs:54:34)\n    at async IncrementalRemoteWriter.beforeBackup (file:///opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/backups/_runners/_writers/IncrementalRemoteWriter.mjs:68:5)\n    at async file:///opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/backups/_runners/_vmRunners/_AbstractXapi.mjs:321:7\n    at async callWriter (file:///opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/backups/_runners/_vmRunners/_Abstract.mjs:33:9)\n    at async IncrementalXapiVmBackupRunner.run (file:///opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/backups/_runners/_vmRunners/_AbstractXapi.mjs:320:5)\n    at async file:///opt/xo/xo-builds/xen-orchestra-202407042240/@xen-orchestra/backups/_runners/VmsXapi.mjs:166:38"
      }
    }
  ],
```

So I decided to check this site for some help, noticed it was recommended to update to the latest version so went ahead and used the install script provided above to import a Debian VM with xo-ce already installed, I start it up and restore my backup of my previous xo-ce and go straight to the backups to attempt it again, however i'm met with an even more severe issue now where all of them fail
```

    {
      "data": {
        "type": "VM",
        "id": "8ca83120-633d-5e6a-8ab9-3b63f9fbf65e",
        "name_label": "APOCVM"
      },
      "id": "1725810672673",
      "message": "backup VM",
      "start": 1725810672673,
      "status": "failure",
      "warnings": [
        {
          "message": "the writer IncrementalRemoteWriter has failed the step writer.beforeBackup() with error EACCES: permission denied, mkdir '/run/xo-server/mounts/e6bdefa2-9f82-4d9b-aae7-93ea36b23829/xo-vm-backups/8ca83120-633d-5e6a-8ab9-3b63f9fbf65e'. It won't be used anymore in this job execution."
        }
      ],
      "end": 1725810672682,
      "result": {
        "errno": -13,
        "code": "EACCES",
        "syscall": "mkdir",
        "path": "/run/xo-server/mounts/e6bdefa2-9f82-4d9b-aae7-93ea36b23829/xo-vm-backups/8ca83120-633d-5e6a-8ab9-3b63f9fbf65e",
        "message": "EACCES: permission denied, mkdir '/run/xo-server/mounts/e6bdefa2-9f82-4d9b-aae7-93ea36b23829/xo-vm-backups/8ca83120-633d-5e6a-8ab9-3b63f9fbf65e'",
        "name": "Error",
        "stack": "Error: EACCES: permission denied, mkdir '/run/xo-server/mounts/e6bdefa2-9f82-4d9b-aae7-93ea36b23829/xo-vm-backups/8ca83120-633d-5e6a-8ab9-3b63f9fbf65e'\nFrom:\n    at NfsHandler.addSyncStackTrace (/opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/fs/dist/local.js:21:26)\n    at NfsHandler._mkdir (/opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/fs/dist/local.js:149:35)\n    at NfsHandler.__mkdir (/opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/fs/dist/abstract.js:435:18)\n    at NfsHandler._mktree (/opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/fs/dist/abstract.js:503:25)\n    at NfsHandler.mktree (/opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/fs/dist/abstract.js:238:16)\n    at IncrementalRemoteWriter.beforeBackup (file:///opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/backups/_runners/_writers/_MixinRemoteWriter.mjs:53:21)\n    at IncrementalRemoteWriter.beforeBackup (file:///opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/backups/_runners/_writers/IncrementalRemoteWriter.mjs:68:17)\n    at file:///opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/backups/_runners/_vmRunners/_AbstractXapi.mjs:326:20\n    at callWriter (file:///opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/backups/_runners/_vmRunners/_Abstract.mjs:33:15)\n    at IncrementalXapiVmBackupRunner._callWriters (file:///opt/xo/xo-builds/xen-orchestra-202409070301/@xen-orchestra/backups/_runners/_vmRunners/_Abstract.mjs:52:14)"
      }
    },
```

Each VM has the same exact error, it complains about permissions, I installed the vm using sudo (not sure if it matters, im not that experienced).

I also went into the config.toml file and set "useSudo = true" as I saw that recommended elsewhere, restarted the VM for good measure and attempted to backup again but am met with the same error.

I'm looking for some help on how to get this working as it might be simpler to resolve the issue than attempt installing xo-ce manually.
(the only reason I did it this way instead of updating my older version is because I seem to have misplaced my credentials and can no longer ssh/console into it)

Thank you in advance.

**Comment by BrianDLC** [comment]
thanks the CEO of Vates told me to come ask you with a :) instead of giving it a few seconds to let me know to check my NFS share, couldnt figure it out but making a new share with the same settings on my NAS resolved the issue.

**Comment by olivierlambert** [comment]
Because you are not the only person in the world asking for assistance. [We are making it very clear in our documentation](https://xen-orchestra.com/docs/community.html) that if you use 3rd party providers to install your XO from the sources, you should see your problems with the provider first, allowing to reduce the burden on our teams to solve environment/configuration issues. It's just common sense to leave more time for our teams to develop the software than solve misconfiguration issues on 3rd party tools we cannot all vet/know ourselves. I hope it's more clear now.
