### ISSUE TITLE
invalid credentials

### ISSUE THREAD

**Issue by dsiminiuk** [ronivay/XenOrchestraInstallerUpdater#35]
After a successful build and creating a new user as well, I am unable to login with the default admin or the new account. "invalid credentials".

I'm not fat fingering the user or pass, I use LastPass to enter it for me.

Is there a file I can update to fix this or is it another problem?
```
root@ubuntu:~# systemctl status xo-server.service
â— xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-04-06 13:00:03 CDT; 2h 41min ago
 Main PID: 653 (node)
    Tasks: 18 (limit: 4623)
   CGroup: /system.slice/xo-server.service
           â”œâ”€653 node /etc/xo/xo-server/bin/xo-server
           â””â”€896 /usr/bin/node /etc/xo/xo-builds/xen-orchestra-202006041608/node_modules/jest-worker/build/workers/processChild.js

Apr 06 15:41:27 ubuntu xo-server[653]:       at _default.authenticateUser (/etc/xo/xo-builds/xen-orchestra-202006041608/packages/xo-server/src/xo-mixins/authentication.js:158:31)
Apr 06 15:41:27 ubuntu xo-server[653]:       at Xo.authenticateUser (/etc/xo/xo-builds/xen-orchestra-202006041608/node_modules/lodash/_createBind.js:23:15)
Apr 06 15:41:27 ubuntu xo-server[653]:       at Strategy._verify (/etc/xo/xo-builds/xen-orchestra-202006041608/packages/xo-server/src/index.js:256:35)
Apr 06 15:41:27 ubuntu xo-server[653]:       at Strategy.authenticate (/etc/xo/xo-builds/xen-orchestra-202006041608/node_modules/passport-local/lib/strategy.js:90:12)
Apr 06 15:41:27 ubuntu xo-server[653]:       at attempt (/etc/xo/xo-builds/xen-orchestra-202006041608/node_modules/passport/lib/middleware/authenticate.js:366:16) {
Apr 06 15:41:27 ubuntu xo-server[653]:     command: 'SINTER',
Apr 06 15:41:27 ubuntu xo-server[653]:     code: 'NR_CLOSED',
Apr 06 15:41:27 ubuntu xo-server[653]:     args: [ 'xo:user_email:admin@admin.net' ]
Apr 06 15:41:27 ubuntu xo-server[653]:   }
Apr 06 15:41:27 ubuntu xo-server[653]: }
```

**Comment by dsiminiuk** [comment]
Good trick! Thanks.
Trying...

**Comment by dsiminiuk** [comment]
Rebuilt on CentOS 7. so far Flawless.
