### ISSUE TITLE
Build fails with error

### ISSUE THREAD

**Issue by dsiminiuk** [ronivay/XenOrchestraInstallerUpdater#62]
**OS Version**: Ubuntu 20.04.1 LTS
**Node.js version**: v12.20.2
**Yarn version**: 1.22.5

**Server specs**
2 vCPUs, 4 GB RAM (VMWare Workstation 16 Pro)

**Issue**
./xo-install.sh --update
Fails with errors
I was able to rollback to a 2021-02-20 installation and it works fine.

I tried apt update and the yarn repo was complaining about invalid key so I updated it.
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
OK
```

**Installation logfile**
```
[info] Checking current node.js version
[ok] node.js version already on 12, checking updates
[info] Fetching Xen Orchestra source code
[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202102230710
[ok] Shutting down xo-server
[info] Updating xen-orchestra from '1bc80eb48' to '69b6d7592'
[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back
[ok] Running installation
[..] Installing plugins
[fail] Something went wrong, exiting. Check /var/log/xo/xo-install.log-202102230710 for more details and use rollback feature if needed
[fail] Removing /etc/xo/xo-builds/xen-orchestra-202102230710 because of failed installation.
```

Contents of /etc/xo/xo-builds/xen-orchestra-202102230710
```
=== CMD ===: apt-get install -y --only-upgrade nodejs yarn

Reading package lists...
Building dependency tree...
Reading state information...
nodejs is already the newest version (12.20.2-deb-1nodesource1).
yarn is already the newest version (1.22.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
=== CMD ===: cd "/etc/xo/xo-src/xen-orchestra"

=== CMD ===: git pull

From https://github.com/vatesfr/xen-orchestra
   a958fe86d..69b6d7592  master              -> origin/master
 + ff346106c...40c959477 fixVmsMigrationHome -> origin/fixVmsMigrationHome  (forced update)
 * [new branch]          listBackupNgDiskPartitions -> origin/listBackupNgDiskPartitions
 * [new branch]          mathieu-fixProxyBiosStrings -> origin/mathieu-fixProxyBiosStrings
Updating a958fe86d..69b6d7592
Fast-forward
 @xen-orchestra/backups/RemoteAdapter.js       | 2 +-
 @xen-orchestra/backups/_DeltaBackupWriter.js  | 2 +-
 @xen-orchestra/backups/_FullBackupWriter.js   | 2 +-
 @xen-orchestra/backups/_PoolMetadataBackup.js | 2 +-
 @xen-orchestra/fs/src/abstract.js             | 2 +-
 @xen-orchestra/fs/src/s3.js                   | 2 +-
 CHANGELOG.unreleased.md                       | 1 +
 7 files changed, 7 insertions(+), 6 deletions(-)
=== CMD ===: cd .

=== CMD ===: rm -rf "/etc/xo/xo-builds/xen-orchestra-202102230710"

=== CMD ===: cp -r "/etc/xo/xo-src/xen-orchestra /etc/xo/xo-builds/xen-orchestra-202102230710"

=== CMD ===: cd /etc/xo/xo-builds/xen-orchestra-202102230710

=== CMD ===: git rev-parse HEAD

=== CMD ===: git rev-parse --short HEAD

=== CMD ===: cd .

=== CMD ===: cd /etc/xo/xo-server

=== CMD ===: git rev-parse HEAD

=== CMD ===: git rev-parse --short HEAD

=== CMD ===: cd .

=== CMD ===: /bin/systemctl stop xo-server

=== CMD ===: cd /etc/xo/xo-builds/xen-orchestra-202102230710 && yarn  && yarn build

yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
error @xen-orchestra/backups@0.4.0: The engine "node" is incompatible with this module. Expected version ">=14.5". Got "12.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
=== CMD ===: ln -sn /etc/xo/xo-builds/xen-orchestra-202102230710/packages/xo-server-audit /etc/xo/xo-builds/xen-orchestra-202102230710/packages/xo-server/node_modules/

ln: target '/etc/xo/xo-builds/xen-orchestra-202102230710/packages/xo-server/node_modules/' is not a directory: No such file or directory
=== CMD ===: rm -rf /etc/xo/xo-builds/xen-orchestra-202102230710
```

```
**xo-server.service log** - no idea where to find this :/
```

copy and paste the output (if available) from command journalctl -u xo-server -n 100
```
Feb 23 07:02:52 xoa.siminiuk.com systemd[1]: Started XO Server.
Feb 23 07:03:12 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:12.997Z xo:main INFO Configuration loaded.
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:13.013Z xo:main INFO Web server listening on http://0.0.0.0:80
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:13.571Z xo:xo-mixins:hooks WARN hook start failure: {
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:   error: Error: Command failed with exit code 5: vgchange -an
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     Logical volume ubuntu-vg/ubuntu-lv contains a filesystem in use.
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     Can't deactivate volume group "ubuntu-vg" with 1 open logical volume(s)
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:       at makeError (/etc/xo/xo-builds/xen-orchestra-202102200200/node_modules/execa/lib/error.js:59:11)
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:       at handlePromise (/etc/xo/xo-builds/xen-orchestra-202102200200/node_modules/execa/index.js:114:26)
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:       at processTicksAndRejections (internal/process/task_queues.js:97:5) {
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     shortMessage: 'Command failed with exit code 5: vgchange -an',
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     command: 'vgchange -an',
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     exitCode: 5,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     signal: undefined,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     signalDescription: undefined,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     stdout: '',
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     stderr: '  Logical volume ubuntu-vg/ubuntu-lv contains a filesystem in use.\n' +
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:       `  Can't deactivate volume group "ubuntu-vg" with 1 open logical volume(s)`,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     failed: true,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     timedOut: false,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     isCanceled: false,
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:     killed: false
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]:   }
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]: }
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:13.859Z xo:main INFO Setting up / → /etc/xo/xo-web/dist/
Feb 23 07:03:13 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:13.884Z xo:plugin INFO register audit
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.027Z xo:plugin INFO register backup-reports
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.064Z xo:plugin INFO register load-balancer
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.129Z xo:plugin INFO register perf-alert
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.181Z xo:plugin INFO register sdn-controller
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.527Z xo:plugin INFO register transport-email
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.824Z xo:plugin INFO register transport-icinga2
Feb 23 07:03:14 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:14.842Z xo:plugin INFO register usage-report
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.018Z xo:plugin INFO successfully register transport-email
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.018Z xo:plugin INFO successfully register transport-icinga2
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.018Z xo:plugin INFO successfully register usage-report
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.018Z xo:plugin INFO successfully register audit
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.018Z xo:plugin INFO successfully register backup-reports
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.020Z xo:plugin INFO successfully register load-balancer
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.020Z xo:plugin INFO successfully register perf-alert
Feb 23 07:03:16 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:03:16.165Z xo:plugin INFO successfully register sdn-controller
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]: _watchEvents TimeoutError: operation timed out
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:     at Promise.call (/etc/xo/xo-builds/xen-orchestra-202102200200/node_modules/promise-toolbox/timeout.js:13:16)
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:     at Xapi._call (/etc/xo/xo-builds/xen-orchestra-202102200200/packages/xen-api/src/index.js:633:37)
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:     at Xapi._watchEvents (/etc/xo/xo-builds/xen-orchestra-202102200200/packages/xen-api/src/index.js:949:31) {
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:   call: {
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:     method: 'event.from',
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:     params: [ [Array], '00000000000047713991,00000000000047474802', 60.1 ]
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]:   }
Feb 23 07:18:52 xoa.siminiuk.com xo-server[144674]: }
Feb 23 07:21:10 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:21:10.791Z xo:main INFO + WebSocket connection (192.168.1.81)
Feb 23 07:23:47 xoa.siminiuk.com systemd[1]: Stopping XO Server...
Feb 23 07:23:47 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:23:47.981Z xo:main INFO SIGTERM caught, closing…
Feb 23 07:23:47 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:23:47.984Z xo:main INFO - WebSocket connection (192.168.1.81)
Feb 23 07:23:48 xoa.siminiuk.com xo-server[144674]: 2021-02-23T13:23:48.353Z xo:main INFO bye :-)
Feb 23 07:23:48 xoa.siminiuk.com systemd[1]: xo-server.service: Succeeded.
Feb 23 07:23:48 xoa.siminiuk.com systemd[1]: Stopped XO Server.
```

**Comment by ronivay** [comment]
Hi,

Thanks. Script should've exited already in the build phase but it didn't. I commited a fix to handle that properly.

The issue here is this:

`error @xen-orchestra/backups@0.4.0: The engine "node" is incompatible with this module. Expected version ">=14.5". Got "12.20.2"
error Found incompatible module.`

There are commits in xen orchestra github from today about that module and i assume it's a work in progress. These happen from time to time when build is done against the master branch. Nothing i can do unfortunately, you should wait and try again later and stick with your current version for now.

I will keep an eye on xen orchestra repository activity if they release any new "from sources" installation instructions. I suppose it's a mistake that it would require node 14.x but we'll see.

**Comment by ronivay** [comment]
Reopened because 14.x version dependency was just released. Need to implement that to this installation script as well.

**Comment by julien-f** [comment]
Hi,

We've just upgraded Node requirement to >=14.5, hope it's not too much troubles for you :slightly_smiling_face: 

We've updated the doc as well.

**Comment by ronivay** [comment]
quick test with node 14.x, stumbled to another error, proxy this time. @julien-f want me to open an issue?

`error /opt/xo/xo-builds/xen-orchestra-202102231453/node_modules/@xen-orchestra/proxy: Command failed.
Exit code: 2
Command: ./scripts/systemd-service-installer
Arguments:
Directory: /opt/xo/xo-builds/xen-orchestra-202102231453/node_modules/@xen-orchestra/proxy
Output:
./scripts/systemd-service-installer: 17: ./scripts/systemd-service-installer: npm_config_prefix: parameter not set`

**Comment by dsiminiuk** [comment]
```
npm cache clean -f
npm install -g n
n latest
  installing : node-v15.10.0
       mkdir : /usr/local/n/versions/node/15.10.0
       fetch : https://nodejs.org/dist/v15.10.0/node-v15.10.0-linux-x64.tar.xz
   installed : v15.10.0 (with npm 7.5.3)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
exit
```
Reset the shell path by logging in again and check node version...
```
node -v
v15.10.0
```

Update xo...
```
./xo-install.sh --update

[info] Checking current node.js version

[ok] node.js version already on 15, checking updates

[info] Fetching Xen Orchestra source code

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202102230853

[ok] Shutting down xo-server

[info] Updating xen-orchestra from '1bc80eb48' to 'a6f4e6771'


[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[ok] Installing plugins

[info] Fixing binary path in systemd service configuration file
[info] Adding WorkingDirectory parameter to systemd service configuration file
[info] Fixing relative path to xo-web installation in xo-server configuration file
[info] Activating modified configuration file

[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web

[info] Replacing systemd service configuration file
[info] Reloading systemd configuration


[info] Starting xo-server...
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open

[fail] Update completed, but looks like there was a problem when starting xo-server/reading journalctl. Please see logs for more details

Control xo-server service with systemctl for stop/start/restart etc.
```

Close! But no cigar.

**Comment by julien-f** [comment]
> quick test with node 14.x, stumbled to another error, proxy this time. @julien-f want me to open an issue or is it still WIP?
> 
> `error /opt/xo/xo-builds/xen-orchestra-202102231453/node_modules/@xen-orchestra/proxy: Command failed. Exit code: 2 Command: ./scripts/systemd-service-installer Arguments: Directory: /opt/xo/xo-builds/xen-orchestra-202102231453/node_modules/@xen-orchestra/proxy Output: ./scripts/systemd-service-installer: 17: ./scripts/systemd-service-installer: npm_config_prefix: parameter not set`

Do not build/install `@xen-orchestra/proxy` it's not intended for open source consumption yet, you will encounter issues.

This specific error occurs when you install dependencies of the proxy as `root`.

**Comment by ronivay** [comment]
> > quick test with node 14.x, stumbled to another error, proxy this time. @julien-f want me to open an issue or is it still WIP?
> > `error /opt/xo/xo-builds/xen-orchestra-202102231453/node_modules/@xen-orchestra/proxy: Command failed. Exit code: 2 Command: ./scripts/systemd-service-installer Arguments: Directory: /opt/xo/xo-builds/xen-orchestra-202102231453/node_modules/@xen-orchestra/proxy Output: ./scripts/systemd-service-installer: 17: ./scripts/systemd-service-installer: npm_config_prefix: parameter not set`
> 
> Do not build/install `@xen-orchestra/proxy` it's not intended for open source consumption yet, you will encounter issues.
> 
> This specific error occurs when you install dependencies of the proxy as `root`.

Yeah figured something like that. Error was the outcome of running `yarn` inside freshly cloned repo content. I'd expect it to be skipped if this shouldn't work yet unless it's going to be available soonish.

**Comment by julien-f** [comment]
It's a script that should run when the package is globally installed/uninstalled, unfortunately npm scripts run even in dev mode, I'll try to find a way to detect it and bail out appropriately.

**Comment by ronivay** [comment]
nodejs will now be upgraded to 14.x. 

Ran tests against Debian 10, Ubuntu 20 and CentOS 8 with success.

@dsiminiuk pull the latest version and if you have issues with 15 version, then downgrade to 14.

**Comment by dsiminiuk** [comment]
@ronivay 

Downloaded latest script, updated

```
[info] Checking current node.js version

[ok] node.js version already on 15, checking updates

[info] Fetching Xen Orchestra source code

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202102240925

[ok] Shutting down xo-server

[info] Updating xen-orchestra from '95c2944f3' to '11801f306'


[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[ok] Installing plugins

[info] Fixing binary path in systemd service configuration file
[info] Adding WorkingDirectory parameter to systemd service configuration file
[info] Fixing relative path to xo-web installation in xo-server configuration file
[info] Activating modified configuration file

[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web

[info] Replacing systemd service configuration file
[info] Reloading systemd configuration


[info] Starting xo-server...
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open

[fail] Update completed, but looks like there was a problem when starting xo-server/reading journalctl. Please see logs for more details

Control xo-server service with systemctl for stop/start/restart etc.
```

Yet, the service is up and I can login. Would reverting to node v14 make a difference?

**Comment by ronivay** [comment]
If build went through and service started, then i doubt downgrading makes a difference. That part of the script looks a line (Starting XO Server...) from service logs that indicates if xo-server has started on a specific port defined in config. It will fail if that cannot be found in 60seconds which usually is more than enough. When it fails, it should print out the lines from service log to the end of scripts own logfile. You can compare that to journalctl -u xo-server output to see if it just started slowly.

**Comment by dsiminiuk** [comment]
And just like that, it stopped kicking out there error. I just let it build every day if there is a new version.
