### ISSUE TITLE
Module bluebird not found

### ISSUE THREAD

**Issue by jt70471** [ronivay/XenOrchestraInstallerUpdater#67]
**OS Version**: Debian 10
**Node.js version**: v14.16.0
**Yarn version**: 1.22.5

**Server specs**
2xVCPU and 3GB memory

**Issue**
After successful build/update, xo-server refused to start due to module bluebird not found

**Installation logfile**
```
xo-install.log is empty
```
**xo-server.service log**
```
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     at Object.<anonymous> (/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server:21:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:   code: 'MODULE_NOT_FOUND',
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:   requireStack: [
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:     '/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]:   ]
Mar 08 14:24:27 xolab.threeputt.org xo-server[4949]: }
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Failed with result 'exit-code'.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 2.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Stopped XO Server.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Started XO Server.
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]: internal/modules/cjs/loader.js:818
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:   throw err;
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:   ^
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]: Error: Cannot find module 'bluebird'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]: Require stack:
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]: - /etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at require (internal/modules/cjs/helpers.js:74:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Object.<anonymous> (/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server:21:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:   code: 'MODULE_NOT_FOUND',
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:   requireStack: [
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:     '/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]:   ]
Mar 08 14:24:27 xolab.threeputt.org xo-server[4956]: }
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Failed with result 'exit-code'.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 3.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Stopped XO Server.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Started XO Server.
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]: internal/modules/cjs/loader.js:818
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:   throw err;
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:   ^
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]: Error: Cannot find module 'bluebird'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]: Require stack:
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]: - /etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at require (internal/modules/cjs/helpers.js:74:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Object.<anonymous> (/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server:21:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:   code: 'MODULE_NOT_FOUND',
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:   requireStack: [
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:     '/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]:   ]
Mar 08 14:24:27 xolab.threeputt.org xo-server[4963]: }
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Failed with result 'exit-code'.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Stopped XO Server.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Started XO Server.
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]: internal/modules/cjs/loader.js:818
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:   throw err;
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:   ^
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]: Error: Cannot find module 'bluebird'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]: Require stack:
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]: - /etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at require (internal/modules/cjs/helpers.js:74:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Object.<anonymous> (/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server:21:18)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:   code: 'MODULE_NOT_FOUND',
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:   requireStack: [
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:     '/etc/xo/xo-builds/xen-orchestra-202103081423/packages/xo-server/bin/xo-server'
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]:   ]
Mar 08 14:24:27 xolab.threeputt.org xo-server[4970]: }
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Failed with result 'exit-code'.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Stopped XO Server.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Start request repeated too quickly.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: xo-server.service: Failed with result 'exit-code'.
Mar 08 14:24:27 xolab.threeputt.org systemd[1]: Failed to start XO Server.
```

**Comment by ronivay** [comment]
I assume you have latest version of this script? Have you run general package update to your OS recently? You should find logfile with build timestamp in filename under logs directory (same path where xo-install.sh is). I think that bluebird error is result of something else.

**Comment by jt70471** [comment]
I always git update before running xo-install.sh and yes, I've done a number of apt upgrades for packages as i do this routinely via ansible. I did remove everything in /etc/xo-server and did a reinstall, which seemed to have worked, so I'm going to close this issue.

Thanks for your quick response.
